classmates=['Michael','Bob','Tracy']
print(classmates)
print(len(classmates))
print(classmates[0])
print(classmates[-1])
classmates.append('Adam')
classmates.insert(0,'Mike')
print(classmates)
print(classmates.pop())
print(classmates)
classmates[1]='Sarah'
print(classmates)
s=['python','java',['asp','php'],'scheme']
print(len(s))
print(s[2][0])
a=[1,2,3,4,5]
print(a)
a.reverse()
print(a)
t=(1,2,3)
print(t)
t=(1,)
print(t)
L=[
    ['Apple','Google','Microsoft'],
    ['Java','Python','Ruby','PHP'],
    ['Adam','Bart','Lisa']
]
print(L[0][0])
print(L[1][1])
print(L[2][2])
